spring:
  application:
    name: school-service
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:trspo
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    schema: classpath:/static/schema.sql, classpath:/static/data.sql
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
server:
  port: 8081

jwt:
  token:
    secret: GiterfilgerKey
    expired: 3600000
    cookie:
      name: AJWT
#    authentication:
#      expire-date: 3600000